#- name: update package
#  shell: apt update

- name: Installing Software on new instance  
  package:
       name:  "{{ item }}"
       state: latest
  with_items:
     - "{{ pack_java }}"
     - "{{ pack_git }}"
     - "{{ pack_apache }}"
     - "{{ pack_maven }}"
     - "{{ pack_tomcat }}"
     - "{{ pack_eclipse }}" 
