

- name: java version
  shell: java -version 2>&1 | awk '/version/' 
  register: javaCat 
  
- name: verify java 
  debug:  
     msg: "{{ javaCat.stdout }}"
 
- name: git version 
  shell: git --version 
  register: gitCat 
  
- name: verify git  
  debug:  
     msg: "{{ gitCat.stdout }}"

- name: Maven version 
  shell: mvn --version 
  register: mvnCat 
  
- name: verify maven  
  debug:  
    msg: "{{ mvnCat.stdout }}"  

- mail:
    host: smtp.gmail.com
    port: 587
    username: "{{ email_uname }}"
    password: "{{ email_pwd }}"
    to: "{{ email_uname_to }}"
    subject: Ansible-report
    body: 'System {{ ansible_hostname }} has been successfully provisioned.'
  delegate_to: localhost

