---
- hosts: local
  connection: local
  gather_facts: False
  tags: provisioning
  become: yes
  roles:
    - ec2-launch


- hosts: launched[-1]
  become: yes
  remote_user: ubuntu
#  gather_facts: True
  tags: installation
  roles:
    - devmachine

